### ISSUE TITLE
MarkdownFilter: incorrect import 'org.markdown.MarkdownProcessor'

### ISSUE THREAD

**Issue by jhansen2015** [myabc/markdownj-ant-utils#1]
**Problem description**: MarkdownFilter has an incorrect import 'org.markdown.MarkdownProcessor' (against markdownj-core 0.4).

**Solution**: Change the import to 'org.markdownj.MarkdownProcessor'.

**Comment by myabc** [comment]
@nautus thank you!

**Comment by jhansen2015** [comment]
@myabc No problem.  Thanks for fixing!
