### ISSUE TITLE
MarkdownFilter: incorrect classname in class javadoc

### ISSUE THREAD

**Issue by jhansen2015** [myabc/markdownj-ant-utils#2]
**Problem description**: The javadoc for MarkdownFilter specifies
`<filterreader classname="org.markdownj.MarkdownFilter"/>`

**Solution**: Change to `<filterreader classname="org.markdownj.antutils.MarkdownFilter"/>`

**Comment by myabc** [comment]
@nautus thanks!

**Comment by jhansen2015** [comment]
@myabc No problem. Thanks for fixing!
